language: java
    
jdk:
  - openjdk11

addons:
  chrome: beta

services:
  - docker

notifications:
  email:
    recipients:
      - angular2guy@gmx.ch
    on_success: always
    on_failure: always

before_install:
  - nvm install 14.15
  - nvm use 14.15

script:
  ./gradlew build docker -PwithAngular=true -PbuildDockerImage=true