webAppName: angularportfoliomgrapp
dbName: postgresserver
webImageName: angular2guy/angularportfoliomgr
webImageVersion: latest
dbImageName: postgres
dbImageVersion: latest
volumeClaimName: postgres-pv-claim
persistentVolumeName: task-pv-volume
webServiceName: angularportfoliomgrservice
dbServiceName: postgresservice
#for production use replace the jwtTokenSecrect value with a random alphanumeric string of the same length or longer
jwtTokenSecrect: secret-key1234567890abcdefghijklmnopqrstuvpxyz

kafkaName: kafkaapp
zookeeperName: zookeeperserver
kafkaImageName: bitnami/kafka
kafkaImageVersion: latest
zookeeperImageName: bitnami/zookeeper
zookeeperImageVersion: latest
kafkaServiceName: kafkaservice
zookeeperServiceName: zookeeperservice

kedaCpuLimit: 60
kedaRequestLimit: 10

secret:
  nameApp: app-env-secret
  nameDb: db-env-secret
  nameKafka: kafka-env-secret
    
envKafka:
  normal: 
    KAFKA_CFG_NODE_ID: 0
    KAFKA_CFG_PROCESS_ROLES: controller,broker
    KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafkaservice:9093
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER     
    
envDb:
  normal: 
    POSTGRES_URL: "jdbc:postgresql://postgresservice:5432/portfolio"
  secret:
    POSTGRES_USER: dbuser
    POSTGRES_PASSWORD: passwordtoreplace
    POSTGRES_DB: portfolio
    
envApp:
  normal: 
    JPA_SHOW_SQL: true
    H2_CONSOLE: false
    SHUTDOWN_PHASE: 10s
#    SPRING_PROFILES_ACTIVE: "prod,prod-kafka,kedatest"
    SPRING_PROFILES_ACTIVE: "prod,prod-kafka"
    KAFKA_SERVICE_NAME: kafkaService
  secret:    
    KAFKA_BOOTSTRAP_SERVERS: kafkaservice:9092 
    KAFKA_SERVER_NAME: kafkaapp
    JWTTOKEN_SECRET: secret-key1234567890abcdefghijklmnopqrstuvwxyz
    POSTGRES_USER: dbuser
    POSTGRES_PASSWORD: passwordtoreplace
    POSTGRES_URL: "jdbc:postgresql://postgresservice:5432/portfolio"
    APIKEY: replacewithAlphavatageApiKey
    APIKEY_RAPIDAPI: replacewithrapidApiKey
    FINANCIAL_DATA_PATH: "/tmp/"    
    TINK_JSON_KEY: '{"primaryKeyId":1047384356,"key":[{"keyData":{"typeUrl":"type.googleapis.com/google.crypto.tink.AesSivKey","value":"EkBtsrB3Aomkmsiq16f9KJQXZX2Y2ZfK3bN1QBBQuxGpSb/5pqQPgqXc5D5FETW6rrBsCv7qIsPyzoEAS2rXPgLx","keyMaterialType":"SYMMETRIC"},"status":"ENABLED","keyId":1047384356,"outputPrefixType":"TINK"}]}'